export const PATHS: { [key: string]: string } = {
  HOME: "/",
  SHOP: "/shop",
  PRODUCT: "/product/:id",
  CART: "/cart",
  CHECKOUT: "/checkout",
  MOMO_RETURN: "/checkout/momo-return",
  ORDERS: "/orders",
  LOGIN: "/login",
  ADMIN_LOGIN: "/admin/login",
  ADMIN: "/admin",
  ADMIN_PRODUCT: "/admin/products/:id",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
};
