export const PATHS: { [key: string]: string } = {
  HOME: "/",
  SHOP: "/shop",
  PRODUCT: "/product/:id",
  CART: "/cart",
  CHECKOUT: "/checkout",
  MOMO_RETURN: "/checkout/momo-return",
  ORDERS: "/orders",
  ORDER_DETAIL: "/orders/:id",
  LOGIN: "/login",
  ADMIN_LOGIN: "/admin/login",
  ADMIN: "/admin",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_COUPONS: "/admin/coupons",
  ADMIN_COUPON_DETAIL: "/admin/coupons/:id",
  ADMIN_PRODUCT: "/admin/products/:id",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
};
